services:
  nextjs_embed:
    build:
      dockerfile: Dockerfile
    container_name: nextjs_embed
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      - VIRTUAL_HOST=player.xoailac.top
      - LETSENCRYPT_HOST=player.xoailac.top
      - LETSENCRYPT_EMAIL=ml2673572@gmail.com
      - VIRTUAL_PORT=3001
    networks:
      - app-network
networks:
  app-network:
    external: true
    name: app-network
